### ISSUE TITLE
Sometimes tiles can not be placed in otherwise legal positions

### ISSUE THREAD

**Issue by sanoy1997** [tsaglam/Carcassonne#4]
![grafik](https://user-images.githubusercontent.com/85501350/148929840-97ec934b-bfd7-4658-b3a1-874ecd39eb2e.png)

As seen in this graphic, the game will not allow me to place the tile in the outlined position. I am currently trying to find out why, but maybe this is a known problem. I would like to play games of carcassonne with a lot of tiles and / or custom tiles, so i really like this program. 

![grafik](https://user-images.githubusercontent.com/85501350/148930410-ce3779e1-9d33-4d1d-9c8d-c8f19fa1fbfc.png)
In this example the piece can also not be placed in the marked spot despite the legality of the placement.

I assume this has something to do with how edges of tiles are defined.

**Comment by tsaglam** [comment]
Ah, yes, this is technically not a bug. It seems it is one of the few homebrew rules left in my implementation. This rule states that you cannot enclose empty spots in the grid, meaning holes are not allowed. It is a homebrew rule I have been using for so long, that I misremembered it to be an official rule. I just checked the different rule sets the existed throughout time but, it is not in there.

I should deal with it as I did with other homebrew rules (like the hand of tiles and fortifying of patterns) and disable it by default but allowing players to re-enable the rule is the game options if desired. Thanks for the issue!

**Comment by sanoy1997** [comment]
i just went back to note, that i found this rule in the code and now feel dumb for thinking its a bug, but if its homebrew then i guess all is fine

**Comment by tsaglam** [comment]
No worries, it is all fine! Your issue made me realize that users should be able to deactivate that rule if desired.
What do you mean by insignias? if you mean emblems, they are already in the game:
![grafik](https://user-images.githubusercontent.com/4396919/148941488-6ba4aa8a-302a-4728-9b5b-29630582c81a.png)

**Comment by sanoy1997** [comment]
yea they are i kinda thought to much about how to differentiate between noninsignia and insignia tiles, guess there is a list of tilestypes somewhere that states which ones have insignias / emblems

**Comment by sanoy1997** [comment]
also if i am not mistaken, the emblems dont turn with the tiles, i think they should

**Comment by tsaglam** [comment]
> there is a list of tile types somewhere that states which ones have insignias / emblems

Emblems are slightly modified in [my game compared to the board game](https://github.com/tsaglam/Carcassonne/wiki/About-this-Project#differences-to-the-board-game). Im my game all castle tiles that make it harder to complete a castle (more than two sides of the tile are an open castle) have emblems, in order to give some incentive for larger castles.

> my problem with emblems was how to distinguish what castle the insignia is on, if there would be more then one castle on the tile like this

Of course, my custom emblem system does not work for cases like this. But this is part of a larger problem: The way I encode tiles is not sufficient for all possible tiles in the board game extensions. For more info check the [wiki](https://github.com/tsaglam/Carcassonne/wiki/About-the-Code#tile-encoding-hardcoding-vs-algorithmic-calculations).

>  the emblems dont turn with the tiles, i think they should

This is a design decision. As this is a computer game and not a board game, there is always "up" and "down",  thus many things do not rotate. You can test that in the tile distribution view by clicking the tiles. This is implemented on purpose and involved quite a lot of work modifying the tiles:

<p align="center">
<img width="200px" alt="The improved meeple placement UI" src="https://user-images.githubusercontent.com/4396919/59276706-1d211580-8c5f-11e9-842e-3f9845abd21a.gif">
</p>

**Comment by sanoy1997** [comment]
this looks nice, on my local version i changed the location the emblems printed on based on the rotation, and linked the emblems to tiles that have Emblem in there name in the enum list, but i forgot to not turn it too, guess i got to fix that

**Comment by tsaglam** [comment]
I implemented a game rule that determines whether enclosing free spots in the grid (so-called enclaves) is legal or not.
Per default, forming these enclaves is legal now, bringing this project in line with the original game. The homebrew rule to forbid enclaves can be enabled in the settings.

**Comment by Cayllen** [comment]
Hey! I saw you did this feature in 2022, but the latest release is in 2021. Is it possible to create another release for this change? Love the game, super good!

> I implemented a game rule that determines whether enclosing free spots in the grid (so-called enclaves) is legal or not. Per default, forming these enclaves is legal now, bringing this project in line with the original game. The homebrew rule to forbid enclaves can be enabled in the settings.

**Comment by tsaglam** [comment]
Yeah, I should really do a release sometime. At the time, I thought I would add more features before the next release. However, I never did since I do not find as much time for this project anymore. I will make a small release as soon as I can find time for it!
